18-playlister-nested-routes/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :playlists, only: [:index, :show, :edit]
  resources :songs, only: [:index, :show, :edit]
  resources :playlistings, only: [:new, :create]

end

18-playlister-nested-routes/app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlistings
  has_many :songs, through: :playlistings
end

18-playlister-nested-routes/app/models/playlisting.rb
class Playlisting < ApplicationRecord

  belongs_to :playlist
  belongs_to :song

end

18-playlister-nested-routes/app/models/song.rb
class Song < ApplicationRecord
  has_many :playlistings
  has_many :playlists, through: :playlistings
end

18-playlister-nested-routes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

18-playlister-nested-routes/app/controllers/playlistings_controller.rb
class PlaylistingsController < ApplicationController

  def new
    @all_songs = Song.all
    @all_playlists = Playlist.all
    @playlisting = Playlisting.new
  end


  def create
    @playlisting_params = params.require(:playlisting).permit(:song_id, :playlist_id)
    @playlisting = Playlisting.create(@playlisting_params)
    redirect_to @playlisting.playlist
  end


end

18-playlister-nested-routes/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  before_action :fetch_playlist, only: [:edit, :update, :delete]

  def index
    @playlists = Playlist.all
  end

  def show
    @all_songs = Song.all
    @all_playlists = Playlist.all
    @playlist = Playlist.includes(:songs).find(params[:id])
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if (@playlist.save)
      redirect_to @playlist
    else
      render :new
    end
  end

  def edit
  end

  def update
    if (@playlist.update(playlist_params))
      redirect_to @playlist
    else
      render :edit
    end
  end

  def delete
    redirect_to playlists_path
  end

  private
  def fetch_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name)
  end

end

18-playlister-nested-routes/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  
  before_action :fetch_song, only: [:show, :edit, :update, :delete]

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if (@song.save)
      redirect_to @song
    else
      render :new
    end
  end

  def edit
  end

  def update
    if (@song.update(song_params))
      redirect_to @song
    else
      render :edit
    end
  end

  def delete
    redirect_to songs_path
  end

  private
  def fetch_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name, :duration)
  end

end

18-playlister-nested-routes/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

18-playlister-nested-routes/app/views/playlists/index.erb
<ol>
<% @playlists.each do |playlist| %>
  <li>
    <%= link_to playlist.name, playlist %>
  </li>
<% end %>
</ol>

18-playlister-nested-routes/app/views/playlists/show.erb
<h1><%= @playlist.name %></h1>

<table>

<% @playlist.songs.each do |song| %>
  <tr>
    <td>
      <%= link_to song.name, song %>
    </td>
    <td>
      <%= song.duration %>
    </td>
  </tr> 
<% end %>
</table>

<h2>Add song</h2>
<%= form_for Playlisting.new do |form| %>

  <%= form.hidden_field :playlist_id, value: @playlist.id %>

  <p>
    <%= form.label :song_id %>
    <%= form.collection_select(:song_id, @all_songs, :id, :name) %>
  </p>

  <%= form.submit %>
<% end %> 

<%= link_to "Edit", edit_playlist_path(@playlist) %>

18-playlister-nested-routes/app/views/songs/index.erb
<ol>
<% @songs.each do |song| %>
  <li>
    <%= link_to song.name, song %>
  </li>
<% end %>
</ol>

18-playlister-nested-routes/app/views/songs/show.erb
<h1><%= @song.name %></h1>
Duration: <%= Time.at(@song.duration).utc.strftime("%M:%S") %>
<%= link_to "Edit", edit_song_path(@song) %>