20.5-css/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :colors, only: [:index] do 
    resources :votes, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create] do
    resources :votes, only: [:index]
  end

  resources :sessions, only: [:new, :create]

  delete "/sessions", to: "sessions#destroy"

  root "colors#index"
end

20.5-css/app/models/color.rb
class Color < ApplicationRecord
  has_many :votes
end

20.5-css/app/models/user.rb
class User < ApplicationRecord
  has_many :votes

  validates_uniqueness_of :username

  # #@user.password = "foo"
  # def password=(value)
  #   self.password_digest = BCrypt::Password.create(value) 
  # end


  # def authenticate(plaintext_password)
  #   BCrypt::Password.new(self.password_digest) == plaintext_password
  # end

  has_secure_password # <<<---- this one line replaces all this ^^^

  def can_vote?
    remaining_votes > 0
  end

  def remaining_votes
    minutes_since_created.floor - self.votes.count + 5
  end

  def next_vote_available_minutes
    minutes_since_created % 1
  end

  private

  def minutes_since_created
    (Time.now.utc - self.created_at) / 60
  end
end

20.5-css/app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :color
end

20.5-css/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :setup_voting_attrs

  private

  def authenticate!
    unless logged_in?
      redirect_to new_session_path
    end
  end

  def authenticated?(user_id)
    current_user_id == user_id
  end

  #just for ruby
  def start_session(user_id)
    log_in_user(user_id)
  end

  def log_in_user(user_id)
    session[:user_id] = user_id
  end

  def logged_in?
    !!current_user_id
  end

  def current_user
    @current_user ||= User.find(current_user_id)
    @current_user
  end

  def log_out!
    session[:user_id] = nil
  end

  def current_user_id
    session[:user_id]
  end
  
  def setup_voting_attrs
    if current_user_id 
      @current_user = current_user
      @minutes_to_next_vote = @current_user.next_vote_available_minutes
      @votes = @current_user.remaining_votes
      @can_vote = @current_user.can_vote?
    end
    @message = flash[:message]
    @errors = flash[:errors]
  end


  # def setup_voting_attrs
  #   # byebug

  #   #first time
  #   unless session[:votes]
  #     session[:votes] = 5
  #   end

  #   @votes = session[:votes]

  #   @can_vote = @votes > 0
  # end

  # def use_one_vote
  #   @votes -= 1
  #   session[:votes] = @votes
  # end



end

20.5-css/app/controllers/colors_controller.rb
class ColorsController < ApplicationController

  def index
    if request.path != colors_path
      redirect_to colors_path
    end
    @colors = Color.includes(:votes).all
  end

end

20.5-css/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  #login form
  def new

  end



  def create
    @user = User.find_by(username: params[:username])
    if (@user && @user.authenticate(params[:password]))
      log_in_user(@user.id)
      flash[:message] = "You are logged in!"
      redirect_to colors_path
    else
      flash[:errors] = ["That didn't match anything we have in our database"]
      redirect_to new_session_path
    end
  end

  #logout
  def destroy
    log_out!
    redirect_to colors_path
  end


  private

  def not_fire_rod_rosenstein

  end
  
end

20.5-css/app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # byebug
      start_session(@user.id)
      flash[:message] = "You are registered!"
      redirect_to colors_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end 

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

20.5-css/app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :"authenticate!"

  # skip_before_action :verify_authenticity_token

  def index
    @params_user = User.find_by(username: params[:user_id])
    if (authenticated?(@params_user.id))
      @user_votes = Vote.includes(:color).where(user_id: @params_user.id)
    else
      redirect_to new_session_path
    end
  end
  
  def create
    if @can_vote
      @vote = Vote.create(color_id: params[:color_id], user_id: session[:user_id])
      # use_one_vote
      flash[:message] = "Thank you for voting for ##{ @vote.color.hex }!";
    else
      @seconds_to_next_vote = 60 - (@minutes_to_next_vote * 60).floor
      flash[:errors] = ["You can't vote for another #{ (@seconds_to_next_vote == 1) ? "second" : (@seconds_to_next_vote.to_s + " seconds") } 💁‍♀️"];
    end
    redirect_to colors_path
  end

  def destroy
    Vote.find(params[:id]).destroy
    redirect_to user_votes_path(current_user.username)
  end

end

20.5-css/app/views/colors/index.erb
<ul class="colors">
  <% @colors.each do |color| %>
  <li class="color" style="background-color: #<%= color.hex %>;">
    #<%= color.hex %>
    <span class="votes">Votes: <%= color.votes.length %>
      <% if @current_user %>
      <%= form_for [color, Vote.new], local: true do |f| %>
      <button type="submit" class="<%= @can_vote ? "vote" : "nope" %>">
        <span class="vote">🗳</span>
        <span class="nope">🙅‍♀️</span>
      </button>
      <% end %>
      <% end %>
    </span>
  </li>
  <% end %>
</ul>

20.5-css/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favorite colors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="auth-nav">
        <% if @current_user %>
          <h3>Logged in as: <%= @current_user.username %></h3>
        <% end %>
        <ul>
          <li><%= link_to "Colors", colors_path %></li>
          <% unless @current_user %>
          <li><a href="<%= new_session_path %>">Log in</a></li>
          <li><a href="<%= new_user_path %>">Sign up</a></li>
          <% else %>
          <li><%= link_to "Votes", user_votes_path(@current_user.username) %></li>
          <li><%= form_tag sessions_path, method: :delete do %>
              <%= submit_tag "Log out" %>
            <% end %>
          </li>
          <% end %>
        </ul>
      </nav>
      <% if @current_user %>
        <h2>Votes remaining: <%= @votes %></h2>
      <% end %>
      <% if @message %>
      <div class="message">
        <%= @message %>
      </div>
      <% end %>
      <% if @errors %>
      <ul class="errors">
        <% @errors.each do |error| %>
          <li>
            <%= error %>
          </li>
        <% end %>
      </ul>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

20.5-css/app/views/users/new.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username, :autocomplete => :off %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>

<% end %>

20.5-css/app/views/votes/index.erb
<h1>Past votes</h1>
<ol>
<% @user_votes.each do |vote| %>
  <li>
  #<%= vote.color.hex %>
  <em><%= time_ago_in_words(vote.created_at) %> ago</em>
  <%= link_to "Delete", color_vote_path(vote.color.id, vote.id), method: :delete %>
  </li>
<% end %>
</ol>