16-rails-forms-validations/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :edit, :update]
  # get "/cats", to: "cats#index"
  # get "/cats/:id", to: "cats#show"
end

16-rails-forms-validations/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

16-rails-forms-validations/app/models/cat.rb
class Cat < ApplicationRecord

  # validates_uniqueness_of :name, message: "help I'm trapped in an activerecord factory"
  # validates :name, { presence: true}, message: "help I'm trapped in an activerecord factory"
  validates :fluffiness, numericality: { less_than_or_equal_to: 10 }
  validates :birth_year, numericality: { 
                                          greater_than: 0, 
                                          only_integer: true,
                                          less_than_or_equal_to: DateTime.now.year }
end

16-rails-forms-validations/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_action :get_cat, only: [:show, :edit, :update]


  # get "/cats" do
  #   @cats = Cat.all
  #   erb: "cats/index"
  # end


  def index
    @cats = Cat.all
  end



  # get "/cats/:id do"
  def show

  end

  def edit

  end


  def update
    # if @cat.year > DateTime.new.year || @cat.fluffiness.class != "Fixnum" || 
    if @cat.update(cat_params)
      redirect_to @cat
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birth_year, :fluffiness)
  end

  def get_cat
    @cat = Cat.find(params[:id])
  end

end

16-rails-forms-validations/app/views/cats/edit.erb
<!-- <form action="/cats/<%= @cat.id %>" method="POST">
  <input type="hidden" value="PUT" name="_method">

</form> -->


<%# form_tag cat_path(@cat), method: :put %>
<% if @cat.errors %>
  <ul>
  <% @cat.errors.full_messages.each do |error| %>
    <li>
      <%= error %>
    </li>
  <% end %>
  </ul>
<% end %>

<%= form_for @cat do |form| %>

<!--   <label for="name">Name</label>
  <input type="text" id="name" name="name" value="<%= @cat.name %>" /> -->

  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :fluffiness %>
    <%= form.text_field :fluffiness %>
  </p>

  <p>
    <%= form.label :birth_year, "Birth Year" %>
    <%= form.text_field :birth_year %>
  </p>

  <%= form.submit "Update #{ @cat.name }" %>
  
  
<% end %>


<%# form_for Cat.new do |form| %>

<%# end %>


<%# form_with model: @cat do |form| %>

<%# end %>

<%# form_with url: cats_path, method: :delete do %>

<%# end %>

16-rails-forms-validations/app/views/cats/index.html.erb
<ol>
  <% @cats.each do |kitty| %>
  <li>
    <%# link_to kitty.name, cat_path(kitty.id) %>
    <%# link_to kitty.name, cat_path(kitty) %>
    <%= link_to kitty.name, kitty %>
  </li>
  <% end %>
</ol>

16-rails-forms-validations/app/views/cats/show.erb
<%# link_to "Edit #{ @cat.name }", edit_cat_path(@cat.id) %>
<%= link_to "Edit #{ @cat.name }", edit_cat_path(@cat) %>
<%# link_to "Doughnuts", "/doughnuts" %>

16-rails-forms-validations/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>